[project]
name = "switchbot-mcp"
version = "0.1.0"
description = "SwitchBot連携用MCPサーバー"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.0.2",
    "mcp>=1.26.0",
    "requests>=2.32.5",
]

[project.scripts]
switchbot-mcp = "switchbot_mcp.switchbot_mcp:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
