[project]
name = "m5-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.0.2",
    "mcp>=1.26.0",
    "requests>=2.32.5",
    "websockets>=13.0",
]

[project.scripts]
m5-mcp = "m5_mcp.m5_mcp:main"


[build-system]
requires = ["hatchling"] 
build-backend = "hatchling.build"